In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('data\DM_data_set.csv')

In [4]:
df

,Unnamed: 0,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
0,0,1354778,0,171,80,34,23,43.509726,1.213191,21,0
1,1,1147438,8,92,93,47,36,21.240576,0.158365,23,0
2,2,1640031,7,115,47,52,35,41.511523,0.079019,23,0
3,3,1883350,9,103,78,25,304,29.582192,1.282870,43,1
4,4,1424119,1,85,59,27,35,42.604536,0.549542,22,0
...,...,...,...,...,...,...,...,...,...,...,...
14995,14995,1490300,10,65,60,46,177,33.512468,0.148327,41,1
14996,14996,1744410,2,73,66,27,168,30.132636,0.862252,38,1
14997,14997,1742742,0,93,89,43,57,18.690683,0.427049,24,0
14998,14998,1099353,0,132,98,18,161,19.791645,0.302257,23,0
14999,14999,1386396,3,114,65,47,512,36.215437,0.147363,34,1

In [5]:
df.isna().sum()

Unnamed: 0                0
PatientID                 0
Pregnancies               0
PlasmaGlucose             0
DiastolicBloodPressure    0
TricepsThickness          0
SerumInsulin              0
BMI                       0
DiabetesPedigree          0
Age                       0
Diabetic                  0
dtype: int64